fix: removed explicit configuration for Dynaconf.
ptoscano/pytest-client-tools pull request #6
Opened 2023-11-16 09:22 UTC by jstavel

I have removed explicit configuration for dynaconf.
I have updated README.md by a new section 'Configuration'.
There is an example how to configure Dynaconf in the section.

2023-11-20 10:42 UTC, jstavel commented
The explicit arguments in Dynacon() take precedence over env vars - I guess. That's why I have remove the arguments. And let anyone specify the main config properties over env vars only.

2023-11-28 07:00 UTC, ptoscano requested changes

2023-11-28 07:00 UTC, ptoscano commented on README.md
> +There is a fixture =test_config= in the defined fixtures.
style: use `` `...` `` rather than `=...=`

2023-11-28 09:11 UTC, jstavel commented on pytest_client_tools/test_config.py
> -            settings_files=["settings.toml", ".secrets.toml"],
I was not able to specify additional file (.secrets.yml) when settings_file arg is presented. .secrets.yml fits better (IMO) to a structured data.

2023-11-28 09:12 UTC, jstavel commented on pytest_client_tools/test_config.py
> -            envvar_prefix="PYTEST_CLIENT_TOOLS",
no problem to use envvar_prefix in the constructor. it makes sense - since it is pytest-client-tools

2024-01-10 10:14 UTC, closed without merging

2024-01-10 10:15 UTC, jstavel commented
This PR is duplicated by another one in a PR queue.